import {
  foodTiffinFixture,
  videoDramaFixture,
  edTechFixture,
  kiranaFixture,
  b2bManufacturingFixture,
  type DomainFixture,
} from './demo-fixtures.ts';

export const DEMO_RUNS = [
  {
    id: 'demo-run-1',
    user_id: '00000000-0000-0000-0000-000000000001',
    idea_text: 'A platform that connects home cooks in tier-2 Indian cities with nearby customers who want homemade tiffin meals delivered to their office on a monthly subscription.',
    language: 'en',
    business_type: 'hybrid',
    status: 'completed' as const,
    error_message: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 2 + 1000 * 45).toISOString(),
  },
  {
    id: 'demo-run-2',
    user_id: '00000000-0000-0000-0000-000000000001',
    idea_text: 'AI-assisted WhatsApp bot for small retail kirana shops to manage inventory, credit book (khata), and auto-order fast-moving items from local distributors.',
    language: 'hi',
    business_type: 'online',
    status: 'completed' as const,
    error_message: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 + 1000 * 38).toISOString(),
  },
  {
    id: 'demo-video',
    user_id: '00000000-0000-0000-0000-000000000001',
    idea_text: 'A short vertical drama series app tailored for regional Indian languages like Bhojpuri, Telugu, and Marathi with pay-per-episode micro-transactions.',
    language: 'mr',
    business_type: 'online',
    status: 'completed' as const,
    error_message: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 12 + 1000 * 30).toISOString(),
  },
  {
    id: 'demo-edtech',
    user_id: '00000000-0000-0000-0000-000000000001',
    idea_text: 'An on-demand peer tutoring platform connecting engineering college students with verified senior university toppers for semester exam preparation.',
    language: 'en',
    business_type: 'online',
    status: 'completed' as const,
    error_message: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 6 + 1000 * 35).toISOString(),
  },
  {
    id: 'demo-saas',
    user_id: '00000000-0000-0000-0000-000000000001',
    idea_text: 'B2B wholesale digital marketplace and automated invoice factoring platform connecting tier-2 Indian precision component manufacturers with corporate buyers.',
    language: 'en',
    business_type: 'online',
    status: 'completed' as const,
    error_message: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 4 + 1000 * 40).toISOString(),
  },
  {
    id: 'demo-food',
    user_id: '00000000-0000-0000-0000-000000000001',
    idea_text: 'A platform that connects home cooks in tier-2 Indian cities with nearby customers who want homemade tiffin meals delivered to their office on a monthly subscription.',
    language: 'en',
    business_type: 'hybrid',
    status: 'completed' as const,
    error_message: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 2 + 1000 * 45).toISOString(),
  },
  {
    id: 'demo-kirana',
    user_id: '00000000-0000-0000-0000-000000000001',
    idea_text: 'AI-assisted WhatsApp bot for small retail kirana shops to manage inventory, credit book (khata), and auto-order fast-moving items from local distributors.',
    language: 'hi',
    business_type: 'online',
    status: 'completed' as const,
    error_message: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 + 1000 * 38).toISOString(),
  },
];

export const DEMO_RESULTS: Record<string, Record<string, unknown>> = {
  'demo-run-1': {
    run_id: 'demo-run-1',
    competitor_status: 'completed',
    tech_status: 'completed',
    financial_status: 'completed',
    legal_status: 'completed',
    global_status: 'completed',
    synthesis_status: 'completed',
    updated_at: new Date().toISOString(),
    competitors: {
      competitors: [
        {
          name: 'Zomato Daily',
          website: 'zomato.com',
          category: 'direct',
          features: ['Scheduled lunch meals', 'Partner kitchen curation', 'Live app delivery tracking'],
          pricing: {
            model: 'subscription',
            starting_price_inr: 2600,
            pricing_details: '₹2,600/month for 20 weekday office lunches',
          },
          strengths: ['Huge existing user base', 'Reliable delivery logistics fleet'],
          weaknesses: ['High commission fee on cooks', 'Not focused on tier-2 home kitchens'],
          market_sentiment: 'mixed',
          sentiment_reason: 'Loved for convenience but high pricing and occasional delivery delays',
          usability_rating: 4.2,
        },
        {
          name: 'EatClub / BOX8',
          website: 'eatclub.com',
          category: 'direct',
          features: ['Cloud kitchen meal plans', 'No delivery fee membership', 'Calorie-labeled meals'],
          pricing: {
            model: 'subscription',
            starting_price_inr: 3200,
            pricing_details: '₹3,200/month average plan',
          },
          strengths: ['Standardized packaging', 'Zero delivery charge model'],
          weaknesses: ['Limited tier-2 city presence', 'Higher price barrier'],
          market_sentiment: 'positive',
          sentiment_reason: 'High hygiene trust among urban IT workforce',
          usability_rating: 4.4,
        },
        {
          name: 'Local Dabba Services (Unorganized)',
          website: 'localdabbas.in',
          category: 'indirect',
          features: ['Unorganized tiffins', 'Cash/UPI payment', 'WhatsApp communication'],
          pricing: {
            model: 'subscription',
            starting_price_inr: 1800,
            pricing_details: '₹1,800/month cash rate',
          },
          strengths: ['Pocket friendly price', 'Authentic homely taste'],
          weaknesses: ['No digital tracking', 'Inconsistent hygiene audits', 'Zero scale'],
          market_sentiment: 'mixed',
          sentiment_reason: 'Affordable daily food but lack of hygiene certifications and reliability',
          usability_rating: 2.9,
        },
      ],
      market_gap: 'A trusted, hygiene-certified home-cooked meal marketplace with WhatsApp-first ordering and route-batched delivery for tier-2 office clusters.',
      competitive_intensity: 'medium',
    },
    tech_feasibility: {
      business_type: 'hybrid',
      technology_stack: {
        frontend: 'Next.js 16 (React 19, Tailwind CSS)',
        backend: 'Node.js serverless route handlers & Supabase Edge Functions',
        database: 'PostgreSQL with Supabase Realtime for order statuses',
        ai_ml: 'Gemini 3.8 Flash for intelligent cook-to-customer route grouping',
        infrastructure: 'Render Web Services + Upstash Redis cache',
      },
      complexity_score: 5,
      mvp_timeline_months: 3,
      full_product_timeline_months: 8,
      engineering_hurdles: [
        'Batching delivery routes within 30-minute lunch windows',
        'Offline-tolerant order tracking in patchy tier-2 network zones',
        'Spike traffic handling during 11:30 AM to 1:00 PM ordering peak',
      ],
      infrastructure_needs: [
        'Managed PostgreSQL with automated daily snapshots',
        'Google Maps & MapmyIndia API for precise geocoding',
        'WhatsApp Business Cloud API for automated notifications',
      ],
      integration_points: [
        'Razorpay & UPI AutoPay for frictionless recurring monthly subscriptions',
        'Shiprocket / Porter API for on-demand neighborhood logistics',
      ],
      security_considerations: [
        'Masking customer phone numbers between cooks and delivery riders',
        'Row Level Security (RLS) ensuring cooks access only their orders',
        'Rate limiting on validation and authentication endpoints',
      ],
      build_vs_buy: 'Buy WhatsApp & Maps infrastructure; build proprietary cook meal scheduler and batching engine.',
      scalability_notes: 'Stateless Node.js services with connection pooling seamlessly handle 10,000+ daily subscriptions.',
      niche_unique_technologies: [
        'FSSAI FoSCoS Public API — real-time home cook license verification during onboarding',
        'Meta WhatsApp Cloud API — menu selection, meal skip/pause, and delivery alerts without an app',
        'Google Maps Distance Matrix API — multi-stop route sequencing for 15-20 tiffin deliveries per rider',
        'Razorpay Route — automated split payments directly to individual cook bank accounts',
        'Upstash Redis distributed locks — cook capacity enforcement (max 25 orders/cook) in real-time',
        'Tamper-Evident QR Code tokens — contactless delivery drop-off verification at customer door',
      ],
    },
    financial_model: {
      market_size_inr: {
        tam: 45000000000,
        sam: 9000000000,
        som: 600000000,
      },
      market_growth_rate_percent: 22,
      revenue_forecast: {
        year1_conservative: 3500000,
        year1_optimistic: 8500000,
        year2_conservative: 18000000,
        year2_optimistic: 42000000,
        year3_conservative: 65000000,
        year3_optimistic: 140000000,
      },
      cost_structure: {
        initial_investment: 1500000,
        monthly_opex: 320000,
        cac: 380,
        ltv: 3200,
        gross_margin_percent: 34,
      },
      break_even_months: 13,
      pricing_strategy: {
        model: 'subscription',
        recommended_price_inr: 2400,
        rationale: 'Priced right at the sweet spot between unorganized ₹1,800 dabbas and ₹3,500 corporate cloud kitchens.',
      },
      bmc: {
        key_partners: ['Home cooks', 'Local delivery riders', 'Biodegradable packaging suppliers'],
        key_activities: ['Cook hygiene audits', 'Route optimization', 'WhatsApp customer care'],
        key_resources: ['Cook community network', 'Routing algorithm', 'Brand trust'],
        value_proposition: 'Hygienic, authentic homemade daily meals delivered hot to your desk at pocket-friendly prices.',
        customer_relationships: ['Automated WhatsApp notifications', 'Dedicated meal plan managers', 'Easy pause/resume'],
        channels: ['Instagram local reels', 'Tech park booth activations', 'Corporate tie-ups'],
        customer_segments: ['Bachelors in IT hubs', 'Single working professionals', 'Students in hostels'],
        cost_structure_items: ['Cook payouts (65%)', 'Rider fees (15%)', 'Customer acquisition & tech (10%)'],
        revenue_streams: ['Subscription commission', 'Priority delivery charges', 'Corporate meal plans'],
      },
      funding_insights: 'High investor interest in tier-2 consumer internet and food-tech solutions focusing on positive unit economics.',
      india_market_notes: 'Tier-2 retention is over 70% due to strong word of mouth and fewer hyper-discounted alternatives.',
    },
    synthesis: {
      viability_verdict: 'viable',
      confidence_score: 86,
      executive_summary: 'The homemade tiffin delivery platform addresses a massive, underserved pain point for office workers in tier-2 Indian cities. Unit economics are robust with positive gross margins from day one, provided kitchen hygiene standards remain strictly audited.',
      top_risks: [
        {
          risk: 'Food quality and hygiene inconsistency across home kitchens',
          severity: 'high',
          mitigation: 'Implement mandatory FSSAI licenses, surprise inspections, and auto-suspension for ratings below 4.0.',
        },
        {
          risk: 'Lunchtime delivery cluster congestion causing late arrivals',
          severity: 'medium',
          mitigation: 'Batch delivery routes 45 minutes ahead with dedicated zone delivery corridors.',
        },
        {
          risk: 'Cook burnout when demand exceeds capacity',
          severity: 'medium',
          mitigation: 'Cap maximum daily orders per cook to 25 meals to preserve sustainable preparation.',
        },
      ],
      top_opportunities: [
        {
          opportunity: 'Exclusive B2B corporate office meal contracts for recurring daily revenue',
          impact: 'high',
          timeframe: 'short-term',
        },
        {
          opportunity: 'Healthy diabetic and high-protein meal subscriptions at premium margins',
          impact: 'high',
          timeframe: 'immediate',
        },
        {
          opportunity: 'Private-label packaged spices and packaging kits sold to onboarded cooks',
          impact: 'medium',
          timeframe: 'long-term',
        },
      ],
      next_steps: [
        { step: 'Onboard 10 vetted home cooks in one pilot tech park neighborhood', priority: 1, timeframe: 'Month 1' },
        { step: 'Launch beta WhatsApp bot to acquire first 50 daily subscriptions', priority: 2, timeframe: 'Month 1-2' },
        { step: 'Validate 30-day retention and unit economics on rider logistics costs', priority: 3, timeframe: 'Month 2-3' },
        { step: 'Release production web app with automated UPI recurring billing', priority: 4, timeframe: 'Month 3-4' },
      ],
      improvement_suggestions: [
        'Offer weekend flexibility to let users skip Saturday/Sunday meals effortlessly',
        'Provide eco-friendly stainless steel tiffin containers with deposit refund',
        'Enable customer-cook messaging with automated translations for local dialects',
      ],
      dimension_scores: {
        market_opportunity: 90,
        competitive_position: 80,
        technical_feasibility: 85,
        financial_viability: 88,
        legal_compliance: 82,
      },
    },
    legal_regulatory: {
      compliance_complexity: 'medium',
      compliance_score: 78,
      is_regulated_sector: true,
      has_blocker_issues: false,
      recommended_entity: 'pvt_ltd',
      entity_rationale: 'A Private Limited Company protects founders from consumer food safety liabilities and is required by institutional seed investors and payment gateways.',
      detected_sectors: ['food_delivery', 'cloud_kitchen', 'consumer_tech'],
      applicable_regulations: [
        'FSSAI Food Safety and Standards Act 2006',
        'Digital Personal Data Protection (DPDP) Act 2023',
        'Consumer Protection (E-Commerce) Rules 2020',
        'GST Act (Food aggregators Section 9(5))',
      ],
      niche_legal_challenges: [
        {
          title: 'Food Poisoning Vicarious Liability & Criminal FIR Exposure',
          niche_context: 'When home cooks prepare meals without centralized industrial QC, an outbreak of food poisoning or allergen contamination leads affected office workers to file consumer complaints and criminal FIRs directly against the aggregator platform and its directors under FSS Act Section 31.',
          legal_precedent_or_statute: 'Food Safety & Standards Act 2006 (Sec 31, 59 & 66 offences by companies) read with BNS 2023 Sec 274/275',
          severity: 'critical',
          operational_impact: 'Director summons by local magistrates, municipal health raids on delivery sorting hubs, sudden frozen settlement accounts by payment gateways.',
          mitigation_strategy: 'Implement mandatory tamper-evident meal seals, retain daily meal samples at regional dispatch hubs for 48 hours, and secure ₹1 Crore Commercial General Food Liability Insurance.',
          contractual_safeguards: [
            'Back-to-back cook indemnity clause in seller onboarding agreement',
            'Mandatory Cook Hygiene & Allergen Self-Declaration protocol',
            'Transit liability disclaimer for third-party courier tampering',
            'Compulsory bilateral arbitration in platform home jurisdiction',
          ],
        },
        {
          title: 'Residential Society (RWA) Bans on Commercial Home Kitchens',
          niche_context: 'Home cooks operate in apartment complexes where Resident Welfare Associations (RWAs) enforce strict bylaws banning commercial activity, heavy courier footfall, and extra LPG cylinder use, threatening cook evictions and gate entry bans.',
          legal_precedent_or_statute: 'State Apartment Ownership Acts & Municipal Corporation Commercial Use Directives',
          severity: 'warning',
          operational_impact: 'Sudden cancellation of lunch batches when top home cooks receive society stoppage notices; delivery riders barred by society security.',
          mitigation_strategy: 'Establish consolidated curb-side neighborhood pickup lockers; cap individual home kitchen output to 25 meals/day to remain within domestic thresholds; verify cook tenancy agreements for home business clearance.',
          contractual_safeguards: [
            'Cook representation of full residential clearance and society permission',
            'Force-majeure clause relieving platform of delivery default upon society stoppage',
            'Strict non-disturbance operational guidelines for meal handovers',
          ],
        },
        {
          title: 'Delivery Rider Gig Worker Status & Code on Social Security 2020',
          niche_context: 'Employing or coordinating two-wheeler tiffin delivery runners across tier-2 cities triggers emerging gig-worker regulations and accident liability during time-sensitive lunch rush delivery windows.',
          legal_precedent_or_statute: 'Code on Social Security 2020 (Sections 113–114) & State Gig Worker Welfare Frameworks',
          severity: 'warning',
          operational_impact: 'Platform liable for mandatory welfare fund cess (1–2% of transaction turnover) and direct financial claims if an un-insured rider suffers a road accident.',
          mitigation_strategy: 'Partner with regional 3PL delivery logistics fleets rather than direct rider payroll; provide automated on-duty group accident micro-insurance (₹5L coverage via Digit/Acko) for active delivery hours.',
          contractual_safeguards: [
            'Independent Contractor Agreement establishing non-exclusive service relationship',
            'Explicit disclaimer of master-servant and employment relationship',
            'Mandatory rider requirement of valid two-wheeler insurance and helmet compliance',
          ],
        },
        {
          title: 'Prepaid Monthly Subscription Lock-in vs. Consumer Refund Rules',
          niche_context: 'The business model charges office workers upfront for 20-30 days of lunch tiffins. Under CCPA 2020 E-commerce Rules, "no-refund" clauses on unconsumed tiffins upon cancellation are deemed unfair contracts.',
          legal_precedent_or_statute: 'Consumer Protection (E-Commerce) Rules 2020 Rule 6 & CCPA Dark Patterns Guidelines 2023',
          severity: 'critical',
          operational_impact: 'Chargebacks through UPI banking apps, National Consumer Helpline grievances, and CCPA penalty notices for restrictive subscription cancellation terms.',
          mitigation_strategy: 'Implement a transparent meal pause/skip feature with 24-hour advance notice; pro-rata wallet refund or credit rollover into next month for skipped meals.',
          contractual_safeguards: [
            'Pro-rata refund and meal credit rollover mechanism clearly defined in T&Cs',
            'Explicit consumer agreement checkbox for 24-hour meal skip notice window',
            '48-hour consumer grievance acknowledgement and 15-day resolution SLA',
          ],
        },
      ],
      regulatory_issues: [
        {
          title: 'Section 9(5) CGST — Aggregator Reverse Charge on Home Cooks',
          description: 'Food delivery platforms must collect and remit 5% GST on behalf of every onboarded home cook — even cooks with no GST number of their own. The platform absorbs the entire tax outflow from Day 1. Many food startups launch unaware of this and face retrospective tax demand with interest and penalties.',
          severity: 'critical',
          regulation_name: 'CGST Act 2017 — Section 9(5) read with Notification No. 17/2021-CT(R)',
          governing_body: 'GSTN / CBIC',
          action_required: 'Register as E-commerce Operator under GST from Day 1 (regardless of turnover). Configure billing engine to withhold and remit 5% GST on each order at platform level.',
          estimated_cost_inr: 40000,
          estimated_timeline_weeks: 3,
        },
        {
          title: 'FSSAI FoSCoS API — Real-Time Cook License Verification Mandate',
          description: 'Under FoSCoS (Food Safety Compliance System), platforms aggregating home cooks must verify each cook\'s FSSAI license number via API before listing them. FSSAI audits food aggregators for unverified listings — penalties up to ₹5 lakh per unverified seller.',
          severity: 'warning',
          regulation_name: 'FSS Act 2006 — FSSAI FoSCoS Platform Verification Guidelines',
          governing_body: 'FSSAI',
          action_required: 'Integrate with FSSAI FoSCoS public API to verify each cook\'s registration number during onboarding and auto-flag expired licenses.',
          estimated_cost_inr: 30000,
          estimated_timeline_weeks: 4,
        },
        {
          title: 'Food Recall & Traceability Obligation on Platform Operator',
          description: 'Under FSS Act Section 28, FSSAI can issue a food recall notice to the platform as the e-commerce food business operator even if the home cook caused the issue. The platform must maintain documented traceability from cook → order → customer retrievable within 24 hours.',
          severity: 'warning',
          regulation_name: 'Food Safety and Standards Act 2006 — Section 28 and FSS (Food Recall Procedure) Regulations 2017',
          governing_body: 'FSSAI / State Food Safety Commissioner',
          action_required: 'Implement order-level traceability logging (cook ID, meal batch, delivery timestamp). Draft a Food Recall SOP and designate a Food Safety Management Representative.',
          estimated_cost_inr: 15000,
          estimated_timeline_weeks: 3,
        },
        {
          title: 'Section 194O TDS — Deduction on Home Cook Payouts',
          description: 'Platforms paying home cooks must deduct 1% TDS before remitting each payout once a cook\'s annual credit exceeds ₹5 lakh — a threshold crossed quickly with 10+ orders/month. Failure to deduct makes the platform the assessee-in-default for the full TDS amount.',
          severity: 'warning',
          regulation_name: 'Income Tax Act 1961 — Section 194O (inserted by Finance Act 2020)',
          governing_body: 'Income Tax Department / CBDT',
          action_required: 'Build TDS deduction into payout engine. Collect PAN from all cooks. File quarterly TDS returns (Form 26Q) and issue Form 16A to each cook quarterly.',
          estimated_cost_inr: 20000,
          estimated_timeline_weeks: 4,
        },
      ],
      required_licenses: [
        {
          license_name: 'FSSAI Central / State E-Commerce Operator License',
          mandatory: true,
          governing_body: 'Food Safety and Standards Authority of India (FSSAI)',
          typical_timeline_weeks: 4,
          typical_cost_inr: 7500,
          notes: 'Mandatory license for platforms aggregating and delivering food from multiple home kitchens.',
        },
        {
          license_name: 'GST Registration (E-Commerce Operator u/s 9(5))',
          mandatory: true,
          governing_body: 'GSTN / CBIC',
          typical_timeline_weeks: 1,
          typical_cost_inr: 0,
          notes: 'Online food aggregators must collect and remit 5% GST on behalf of onboarded home chefs.',
        },
        {
          license_name: 'Section 194O TDS Registration — Cook Payout Compliance',
          mandatory: true,
          governing_body: 'Income Tax Department / CBDT',
          typical_timeline_weeks: 1,
          typical_cost_inr: 0,
          notes: 'Platforms paying home cooks must deduct 1% TDS before each payout and file Form 26Q quarterly. Requires TAN (Tax Deduction Account Number) from NSDL. Most food-tech founders miss this until their first CA audit.',
        },
      ],
      data_privacy: {
        is_data_fiduciary: true,
        handles_children_data: false,
        cross_border_transfer: false,
        dpdp_obligations: [
          'Collect explicit consent for food delivery locations and dietary preferences',
          'Implement phone number masking between couriers and customers',
          'Appoint a published Data Grievance Redressal Officer',
          'Provide automated account and data deletion requests for subscribers',
        ],
      },
      ip_recommendations: {
        trademark_urgency: 'within_6_months',
        patent_potential: false,
        trademark_classes: [35, 43],
        ip_risks: [
          'Brand name imitation by local cloud kitchen networks in Class 43',
          'Protect proprietary route batching dispatch logic through NDA and copyright',
        ],
      },
      tax_overview: {
        gst_rate_percent: 5,
        gst_registration_required: true,
        startup_india_eligible: true,
        tax_notes: 'Food delivery services incur a flat 5% GST without input tax credit under Section 9(5). DPIIT Startup India certificate grants 3-year income tax exemption under Section 80-IAC.',
      },
      legal_executive_summary: 'The most critical non-obvious legal risk is Section 9(5) CGST — the platform must remit 5% GST on every order from Day 1 even if the home cook has no GST number. The second key trap is FSSAI\'s FoSCoS API mandate: listing unverified home cooks triggers penalties up to ₹5 lakh per unverified seller. Food recall traceability obligations under FSS Act Section 28 and Section 194O TDS on cook payouts add compliance complexity that most food-tech founders discover only after launch. Incorporating as a Private Limited Company is strongly advised to insulate founders from personal liability under FSS Act Section 31.',
      immediate_action_items: [
        'Register as E-Commerce Operator under GST from Day 1 — Section 9(5) reverse charge applies regardless of turnover',
        'Integrate FSSAI FoSCoS API to verify each cook\'s license number during onboarding — never list unverified cooks',
        'Build 1% TDS deduction (Section 194O) into cook payout engine before first payment — get TAN from NSDL',
        'Apply for FSSAI Central E-Commerce FBO License on FoSCoS portal (6–8 weeks, ₹7,500)',
        'Draft Food Recall SOP and designate a Food Safety Management Representative before going live',
      ],
      estimated_compliance_setup_cost_inr: 55000,
    },
    global_benchmarks: {
      has_international_precedents: true,
      novelty_assessment: 'globally_proven',
      global_summary: 'The curated home-cooked / chef-to-consumer meal delivery subscription model has seen major venture-backed success in North America and Europe. Companies like Shef (US), CookUnity (US), and Dabbawal (UK) proved consumer demand for authentic, localized home-style cooking over industrial restaurant food, while scaling via hub-and-spoke delivery clusters.',
      geographical_distribution: ['United States', 'United Kingdom', 'Canada', 'Singapore'],
      similar_businesses: [
        {
          name: 'Shef',
          country: 'United States',
          website_or_domain: 'shef.com',
          year_founded: 2019,
          business_overview: 'Two-sided marketplace connecting food safety-certified home cooks with regional diners seeking authentic ethnic home-cooked meals delivered 2-3 times per week.',
          implementation_model: 'Asset-light marketplace; food safety background checks; scheduled batch deliveries to optimize route density rather than on-demand 30-min courier dispatch.',
          monetization_model: '15-20% commission on cook meal sales plus variable delivery service fee paid by subscribers.',
          traction_and_scale: 'Raised $100M+ from Andreessen Horowitz (a16z), Y Combinator, and celebrity angels; operating across 10+ major US metropolitan regions.',
          current_status: 'active',
          key_learnings_for_india: 'Scheduled batching is mandatory for unit economics. Trying to deliver home meals on-demand kills margins; scheduled 11:30 AM – 1:00 PM batch windows preserve route density.',
        },
        {
          name: 'CookUnity',
          country: 'United States',
          website_or_domain: 'cookunity.com',
          year_founded: 2015,
          business_overview: 'Chef-to-consumer subscription meal platform where independent culinary chefs prepare fresh, chilled gourmet meals packaged in sustainable trays for weekly home/office delivery.',
          implementation_model: 'Shared licensed production commissary hubs combined with refrigerated next-day regional courier logistics.',
          monetization_model: 'Weekly recurring subscription ($11–$13 per meal) with revenue share split between platform and partner chefs.',
          traction_and_scale: 'Raised over $70M, expanding to multiple US metros with 5M+ meals delivered annually.',
          current_status: 'active',
          key_learnings_for_india: 'Quality control and hygienic packaging are the primary retention drivers. Providing standardized stainless steel or tamper-proof containers creates trust.',
        },
        {
          name: 'WoodSpoon',
          country: 'United States',
          website_or_domain: 'eatwoodspoon.com',
          year_founded: 2019,
          business_overview: 'Community-based online food delivery service connecting local home chefs with neighborhood diners seeking warm, handcrafted cultural comfort meals.',
          implementation_model: 'Hyper-local neighborhood radius matching cooks within a 3-mile delivery perimeter.',
          monetization_model: 'Take-rate commission per order + courier delivery fee.',
          traction_and_scale: 'Raised $14M Series A, operating across New York and New Jersey.',
          current_status: 'active',
          key_learnings_for_india: 'Tight geographic radius keeps food temperature hot and minimizes courier churn in high-traffic tier-2 Indian city centers.',
        },
      ],
      market_differences_vs_india: 'In the US, consumer basket sizes average $15–$25 per meal, accommodating higher third-party courier fees ($5–$8). In Tier-2 India, daily lunch meals are price-sensitive (₹80–₹140), making unit margins tighter. However, India boasts far higher delivery density, lower courier labor costs, and higher weekday repeat subscription retention (>60%), provided logistics are batched.',
      lessons_for_indian_founders: [
        'Never operate on an on-demand 30-minute delivery model; mandate 24-hour advance meal reservations to enable route optimization',
        'Subsidize standardized packaging and tamper-proof safety seals for cooks to address hygiene skepticism',
        'Deploy WhatsApp bot ordering with UPI AutoPay to minimize app download friction in tier-2 cities',
        'Focus first on dense corporate tech parks and coaching hub zones to achieve 15+ deliveries per building cluster',
      ],
    },
  },
};

function fixtureToDemoResult(runId: string, fixture: DomainFixture) {
  return {
    run_id: runId,
    competitor_status: 'completed',
    tech_status: 'completed',
    financial_status: 'completed',
    legal_status: 'completed',
    global_status: 'completed',
    synthesis_status: 'completed',
    updated_at: new Date().toISOString(),
    competitors: fixture.competitors,
    tech_feasibility: fixture.tech,
    financial_model: fixture.finance,
    legal_regulatory: fixture.legal,
    global_benchmarks: fixture.global,
    synthesis: fixture.synthesis,
  };
}

// Map each demo idea to its dedicated domain-tailored intelligence fixture
DEMO_RESULTS['demo-run-1'] = fixtureToDemoResult('demo-run-1', foodTiffinFixture);
DEMO_RESULTS['demo-food'] = DEMO_RESULTS['demo-run-1'];
DEMO_RESULTS['demo-run-2'] = fixtureToDemoResult('demo-run-2', kiranaFixture);
DEMO_RESULTS['demo-kirana'] = DEMO_RESULTS['demo-run-2'];
DEMO_RESULTS['demo-video'] = fixtureToDemoResult('demo-video', videoDramaFixture);
DEMO_RESULTS['demo-edtech'] = fixtureToDemoResult('demo-edtech', edTechFixture);
DEMO_RESULTS['demo-saas'] = fixtureToDemoResult('demo-saas', b2bManufacturingFixture);

